sudo: required
language: java
jdk: oraclejdk7

env:
    global:
        - ANDROID_SDK_VER = "r24.2"

before_install:
    - chmod +x gradlew
    - sudo apt-get update -qq
    # install the 32 bits libraries (required since travis uses 64 bit systems)
    - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch

    # get the android sdk
    - wget "http://dl.google.com/android/android-sdk_r24.2-linux.tgz"

    # install the android sdk
    - tar -zxf android-sdk_r24.2-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    #- chmod +x android

    # get and install android sdk tools such as the platform and build tools
    - android update sdk --filter platform-tools --no-ui --force
    - android update sdk --all --filter build-tools-20.0.0 --no-ui --force
    - android update sdk --filter android-21 --no-ui --force
    - android update sdk --filter extra-android-support --no-ui --force
    - android update sdk --filter extra-android-m2repository --no-ui --force
    - android update sdk --filter extra-google-m2repository --no-ui --force

before_script:
    - chmod +x gradlew

script:
    - ./gradlew clean build test check